spring.application.name=lambda-parser-function
server.port=8085

cloud.aws.credentials.access-key=${ACCESS_KEY}
cloud.aws.credentials.secret-key=${SECRET-KEY}
cloud.aws.credentials.region=${REGION}

cloud.aws.s3.bucket-name=${BUCKET_NAME}

cloud.aws.sqs.queue-name=${QUEUE_NAME}
cloud.aws.sqs.queue-url=${QUEUE_URL}

spring.data.mongodb.uri=mongodb://localhost:27017/stats-tg-chat-db